// Fictional demonstration documents only (per Kweli_V3_Master_Kickoff.md section 11 / 13).
// Deliberately spans multiple industries and includes near-duplicate filenames
// with different outcomes — the point is that a filename or file itself never
// proves authenticity, only the registered fingerprint does.
//
// Each entry's `sha256` is the real digest of the corresponding file in
// public/sample-documents/, generated by scripts/generate-sample-pdfs.mjs.
// The Verification Demo hashes whatever the visitor actually uploads and
// looks it up here — nothing is decided by which library row was clicked.

export type Outcome = "verified" | "failed" | "not-found";

export type VerifiedDetails = {
  issuer: string;
  documentType: string;
  issuedDate: string;
  registeredDate: string;
  registeredBy: string;
};

export type FailedDetails = {
  issuer: string;
  documentType: string;
  reasons: string[];
};

export type NotFoundDetails = {
  issuer: string;
  reasons: string[];
};

export type DemoDocument = {
  id: string;
  filename: string;
  fileSize: string;
  assetPath: string;
  sha256: string;
  outcome: Outcome;
  verified?: VerifiedDetails;
  failed?: FailedDetails;
  notFound?: NotFoundDetails;
};

export const demoDocuments: DemoDocument[] = [
  // Education
  {
    id: "degree-cert",
    filename: "Degree Certificate.pdf",
    fileSize: "4.4 KB",
    assetPath: "/sample-documents/degree-cert.pdf",
    sha256: "afec425b60d54e3bf808b4f27a585f38c283d93e5e500398f0bc3e30719255e3",
    outcome: "verified",
    verified: {
      issuer: "Kweli University",
      documentType: "Degree Certificate",
      issuedDate: "17 March 2026",
      registeredDate: "17 March 2026 • 09:41 EAT",
      registeredBy: "Registrar Office",
    },
  },
  {
    id: "degree-cert-final",
    filename: "Degree Certificate Final.pdf",
    fileSize: "4.3 KB",
    assetPath: "/sample-documents/degree-cert-final.pdf",
    sha256: "5b67dcf6dfb3f1e8aca92358ce47e884e03ed44caf5284aacbf7d4b5368e1e4c",
    outcome: "failed",
    failed: {
      issuer: "Kweli University",
      documentType: "Degree Certificate",
      reasons: ["Pages replaced", "Content modified"],
    },
  },
  {
    id: "degree-cert-scan",
    filename: "Degree Certificate Scan.pdf",
    fileSize: "4.4 KB",
    assetPath: "/sample-documents/degree-cert-scan.pdf",
    sha256: "de5cd2e172d40b294dcbe00064e66752731639d54ad147c3baee3c4a5525fb76",
    outcome: "not-found",
    notFound: {
      issuer: "Kweli University",
      reasons: ["Never registered", "Incorrect document"],
    },
  },
  // Insurance
  {
    id: "repair-estimate",
    filename: "Repair Estimate.pdf",
    fileSize: "6.8 KB",
    assetPath: "/sample-documents/repair-estimate.pdf",
    sha256: "0c3b9c0b277dbcb488cd4dd3921bfdb691718a413e92d0591ab06d293581f2af",
    outcome: "failed",
    failed: {
      issuer: "Northline Motors",
      documentType: "Repair Estimate",
      reasons: ["Edited", "Content modified"],
    },
  },
  {
    id: "repair-estimate-final",
    filename: "Repair Estimate Final.pdf",
    fileSize: "6.8 KB",
    assetPath: "/sample-documents/repair-estimate-final.pdf",
    sha256: "f08bd5607f04447e7029474d972a983f364eec735a6cd2fab6e4e228172bf1fa",
    outcome: "verified",
    verified: {
      issuer: "Northline Motors",
      documentType: "Repair Estimate",
      issuedDate: "2 June 2026",
      registeredDate: "2 June 2026 • 14:12 EAT",
      registeredBy: "Claims Department",
    },
  },
  {
    id: "repair-estimate-copy",
    filename: "Repair Estimate Copy.pdf",
    fileSize: "6.8 KB",
    assetPath: "/sample-documents/repair-estimate-copy.pdf",
    sha256: "bf8743f6f0ed95d5e7e5f513c8e95ec3fcd313efe8219d8ae07964814a3d3438",
    outcome: "not-found",
    notFound: {
      issuer: "Northline Motors",
      reasons: ["Never registered", "Incorrect document"],
    },
  },
  {
    id: "insurance-claim",
    filename: "Insurance Claim Form.pdf",
    fileSize: "6.2 KB",
    assetPath: "/sample-documents/insurance-claim.pdf",
    sha256: "8a974dd48d39795d661bb59d174df2cd61df9d4704b3634a9b569633015e04f5",
    outcome: "verified",
    verified: {
      issuer: "Turaco Underwriters",
      documentType: "Insurance Claim Form",
      issuedDate: "9 May 2026",
      registeredDate: "9 May 2026 • 16:30 EAT",
      registeredBy: "Claims Department",
    },
  },
  // Healthcare
  {
    id: "lab-report",
    filename: "Laboratory Report.pdf",
    fileSize: "6.3 KB",
    assetPath: "/sample-documents/lab-report.pdf",
    sha256: "45d558ab7e8898a155b2213b2f34bce11b8ee317cea7271fb7e7c24a0af4e5a3",
    outcome: "verified",
    verified: {
      issuer: "Verstlab Diagnostics",
      documentType: "Laboratory Report",
      issuedDate: "28 April 2026",
      registeredDate: "28 April 2026 • 11:05 EAT",
      registeredBy: "Records Office",
    },
  },
  {
    id: "lab-report-scan",
    filename: "Laboratory Report Scan.pdf",
    fileSize: "6.2 KB",
    assetPath: "/sample-documents/lab-report-scan.pdf",
    sha256: "7ce3154cac7ff1248366adcf6aeb7d0a69e76706b17eb6bb3e400aec13401581",
    outcome: "not-found",
    notFound: {
      issuer: "Verstlab Diagnostics",
      reasons: ["Never registered", "Incorrect document"],
    },
  },
  // Trade
  {
    id: "organic-cert",
    filename: "Organic Certificate.pdf",
    fileSize: "4.3 KB",
    assetPath: "/sample-documents/organic-cert.pdf",
    sha256: "a373cb9ea3535e85a36a0b14d89d5458880f7109af3fa50b83b86882b4a871e9",
    outcome: "verified",
    verified: {
      issuer: "Cropnuts Certification Body",
      documentType: "Organic Certificate",
      issuedDate: "14 January 2026",
      registeredDate: "14 January 2026 • 08:52 EAT",
      registeredBy: "Certification Board",
    },
  },
  {
    id: "organic-cert-updated",
    filename: "Organic Certificate Updated.pdf",
    fileSize: "4.4 KB",
    assetPath: "/sample-documents/organic-cert-updated.pdf",
    sha256: "8fafe5dfcd986b8cb9d911db3f8c3295363f2de1920bb82cbc7ae7ff58ca4c4b",
    outcome: "failed",
    failed: {
      issuer: "Cropnuts Certification Body",
      documentType: "Organic Certificate",
      reasons: ["Edited", "Content modified"],
    },
  },
  {
    id: "shipping-manifest",
    filename: "Shipping Manifest.pdf",
    fileSize: "6.0 KB",
    assetPath: "/sample-documents/shipping-manifest.pdf",
    sha256: "8d2d76196ce10d711e507a1f7f7f7979c29b04542b78c2bea74cc6a3731b1577",
    outcome: "failed",
    failed: {
      issuer: "Meridian Freight Lines",
      documentType: "Shipping Manifest",
      reasons: ["Edited", "Signature mismatch"],
    },
  },
  // Government
  {
    id: "building-permit",
    filename: "Building Permit.pdf",
    fileSize: "5.4 KB",
    assetPath: "/sample-documents/building-permit.pdf",
    sha256: "31a26278a5912c985dfebb3ee7a5a5620c028ee62a822b6fec7c9184e26d119c",
    outcome: "not-found",
    notFound: {
      issuer: "Unknown",
      reasons: ["Unknown issuer", "Incorrect document"],
    },
  },
  // Banking
  {
    id: "bank-guarantee",
    filename: "Bank Guarantee.pdf",
    fileSize: "5.3 KB",
    assetPath: "/sample-documents/bank-guarantee.pdf",
    sha256: "dcd0f103464e18b30909bb8aea0e7999a8eac5bbed8a42c7d0b2a5750f126fe5",
    outcome: "verified",
    verified: {
      issuer: "Zenith Commercial Bank",
      documentType: "Bank Guarantee",
      issuedDate: "22 February 2026",
      registeredDate: "22 February 2026 • 10:18 EAT",
      registeredBy: "Branch Operations",
    },
  },
];

export function findDocumentByHash(sha256: string): DemoDocument | undefined {
  const normalized = sha256.toLowerCase();
  return demoDocuments.find((doc) => doc.sha256 === normalized);
}
