// Fictional demonstration documents only (per Kweli_V3_Master_Kickoff.md section 11 / 13).
// Deliberately spans multiple industries and includes near-duplicate filenames
// with different outcomes — the point is that a filename or file itself never
// proves authenticity, only the registered fingerprint does.
//
// Each entry's `sha256` is the real digest of the corresponding file in
// public/sample-documents/, generated by scripts/generate-sample-pdfs.mjs.
// The Verification Demo hashes whatever the visitor actually uploads and
// looks it up here — nothing is decided by which library row was clicked.

export type Outcome = "verified" | "failed" | "not-found";

export type VerifiedDetails = {
  issuer: string;
  documentType: string;
  issuedDate: string;
  registeredDate: string;
  registeredBy: string;
};

export type FailedDetails = {
  issuer: string;
  documentType: string;
  reasons: string[];
};

export type NotFoundDetails = {
  issuer: string;
  reasons: string[];
};

export type DemoDocument = {
  id: string;
  filename: string;
  fileSize: string;
  assetPath: string;
  sha256: string;
  outcome: Outcome;
  verified?: VerifiedDetails;
  failed?: FailedDetails;
  notFound?: NotFoundDetails;
};

export const demoDocuments: DemoDocument[] = [
  // Education
  {
    id: "degree-cert",
    filename: "Degree Certificate.pdf",
    fileSize: "955 B",
    assetPath: "/sample-documents/degree-cert.pdf",
    sha256: "385e96b31dfd305946230e2d915f943b8d4b7539b2b19ffa502aecbfa606eaeb",
    outcome: "verified",
    verified: {
      issuer: "Kweli University",
      documentType: "Degree Certificate",
      issuedDate: "17 March 2026",
      registeredDate: "17 March 2026 • 09:41 EAT",
      registeredBy: "Registrar Office",
    },
  },
  {
    id: "degree-cert-final",
    filename: "Degree Certificate Final.pdf",
    fileSize: "965 B",
    assetPath: "/sample-documents/degree-cert-final.pdf",
    sha256: "4c8eac50814273dd5e591c89ed6c5a918656d8b591c6c040079dd915b465b081",
    outcome: "failed",
    failed: {
      issuer: "Kweli University",
      documentType: "Degree Certificate",
      reasons: ["Pages replaced", "Content modified"],
    },
  },
  {
    id: "degree-cert-scan",
    filename: "Degree Certificate Scan.pdf",
    fileSize: "972 B",
    assetPath: "/sample-documents/degree-cert-scan.pdf",
    sha256: "2b2282516be94ba6e95c64159ee7186ff4e5989f44b044953c4b7d38a698da03",
    outcome: "not-found",
    notFound: {
      issuer: "Kweli University",
      reasons: ["Never registered", "Incorrect document"],
    },
  },
  // Insurance
  {
    id: "repair-estimate",
    filename: "Repair Estimate.pdf",
    fileSize: "949 B",
    assetPath: "/sample-documents/repair-estimate.pdf",
    sha256: "6b3980510ad67a052411fee9805f323ca26ad1c1966e50032c2c9dd45764c4cb",
    outcome: "failed",
    failed: {
      issuer: "Northline Motors",
      documentType: "Repair Estimate",
      reasons: ["Edited", "Content modified"],
    },
  },
  {
    id: "repair-estimate-final",
    filename: "Repair Estimate Final.pdf",
    fileSize: "959 B",
    assetPath: "/sample-documents/repair-estimate-final.pdf",
    sha256: "a0e174696d492ac977d6b53c42c1be1386fbdbda0b1644f7935edd091f97aa3e",
    outcome: "verified",
    verified: {
      issuer: "Northline Motors",
      documentType: "Repair Estimate",
      issuedDate: "2 June 2026",
      registeredDate: "2 June 2026 • 14:12 EAT",
      registeredBy: "Claims Department",
    },
  },
  {
    id: "repair-estimate-copy",
    filename: "Repair Estimate Copy.pdf",
    fileSize: "958 B",
    assetPath: "/sample-documents/repair-estimate-copy.pdf",
    sha256: "a49a52e2483192b3bcf93f589229df13dcf93fa79b4ba7969f76327c24c21ef0",
    outcome: "not-found",
    notFound: {
      issuer: "Northline Motors",
      reasons: ["Never registered", "Incorrect document"],
    },
  },
  {
    id: "insurance-claim",
    filename: "Insurance Claim Form.pdf",
    fileSize: "962 B",
    assetPath: "/sample-documents/insurance-claim.pdf",
    sha256: "95e572eb99cc97dca399e0e1cf3dd6e6a56965bbc6ea665cd1a5218e252f42c2",
    outcome: "verified",
    verified: {
      issuer: "Turaco Underwriters",
      documentType: "Insurance Claim Form",
      issuedDate: "9 May 2026",
      registeredDate: "9 May 2026 • 16:30 EAT",
      registeredBy: "Claims Department",
    },
  },
  // Healthcare
  {
    id: "lab-report",
    filename: "Laboratory Report.pdf",
    fileSize: "957 B",
    assetPath: "/sample-documents/lab-report.pdf",
    sha256: "40e26c01d9dd5f07153ac16d4fb211dd37d5e5224944fdd305670d60b35b8245",
    outcome: "verified",
    verified: {
      issuer: "Verstlab Diagnostics",
      documentType: "Laboratory Report",
      issuedDate: "28 April 2026",
      registeredDate: "28 April 2026 • 11:05 EAT",
      registeredBy: "Records Office",
    },
  },
  {
    id: "lab-report-scan",
    filename: "Laboratory Report Scan.pdf",
    fileSize: "974 B",
    assetPath: "/sample-documents/lab-report-scan.pdf",
    sha256: "1729b31a088268582b48a238cd6926b5622c535ade7d02410a0d078c28412a74",
    outcome: "not-found",
    notFound: {
      issuer: "Verstlab Diagnostics",
      reasons: ["Never registered", "Incorrect document"],
    },
  },
  // Trade
  {
    id: "organic-cert",
    filename: "Organic Certificate.pdf",
    fileSize: "968 B",
    assetPath: "/sample-documents/organic-cert.pdf",
    sha256: "a8be12206989602200e32191966335245df5cd9ab966e85eedc13adccc100539",
    outcome: "verified",
    verified: {
      issuer: "Cropnuts Certification Body",
      documentType: "Organic Certificate",
      issuedDate: "14 January 2026",
      registeredDate: "14 January 2026 • 08:52 EAT",
      registeredBy: "Certification Board",
    },
  },
  {
    id: "organic-cert-updated",
    filename: "Organic Certificate Updated.pdf",
    fileSize: "980 B",
    assetPath: "/sample-documents/organic-cert-updated.pdf",
    sha256: "62d0cf2434e8fcf4bff9f7b18f937cbc0046e42974fda51a31e288a877ec55c6",
    outcome: "failed",
    failed: {
      issuer: "Cropnuts Certification Body",
      documentType: "Organic Certificate",
      reasons: ["Edited", "Content modified"],
    },
  },
  {
    id: "shipping-manifest",
    filename: "Shipping Manifest.pdf",
    fileSize: "959 B",
    assetPath: "/sample-documents/shipping-manifest.pdf",
    sha256: "e31ad61b8aa6fefa0439e30839a25c3092aff78372efaf74c24a2318499f7b51",
    outcome: "failed",
    failed: {
      issuer: "Meridian Freight Lines",
      documentType: "Shipping Manifest",
      reasons: ["Edited", "Signature mismatch"],
    },
  },
  // Government
  {
    id: "building-permit",
    filename: "Building Permit.pdf",
    fileSize: "958 B",
    assetPath: "/sample-documents/building-permit.pdf",
    sha256: "114e206b28f0c38ecf5b5e00e1913f41b388ca284279923c791d17b48260d579",
    outcome: "not-found",
    notFound: {
      issuer: "Unknown",
      reasons: ["Unknown issuer", "Incorrect document"],
    },
  },
  // Banking
  {
    id: "bank-guarantee",
    filename: "Bank Guarantee.pdf",
    fileSize: "953 B",
    assetPath: "/sample-documents/bank-guarantee.pdf",
    sha256: "cd9964335a5bbb70026f773ab740bbbdc60e716e6d2da06a507b6d07caf19687",
    outcome: "verified",
    verified: {
      issuer: "Zenith Commercial Bank",
      documentType: "Bank Guarantee",
      issuedDate: "22 February 2026",
      registeredDate: "22 February 2026 • 10:18 EAT",
      registeredBy: "Branch Operations",
    },
  },
];

export function findDocumentByHash(sha256: string): DemoDocument | undefined {
  const normalized = sha256.toLowerCase();
  return demoDocuments.find((doc) => doc.sha256 === normalized);
}
