// Fictional demonstration documents only (per Kweli_V3_Master_Kickoff.md section 11 / 13).
// Deliberately spans multiple industries and includes near-duplicate filenames
// with different outcomes — the point is that a filename or file itself never
// proves authenticity, only the registered fingerprint does.
//
// Each entry's `sha256` is the real digest of the corresponding file in
// public/sample-documents/, generated by scripts/generate-sample-pdfs.mjs.
// The Verification Demo hashes whatever the visitor actually uploads and
// looks it up here — nothing is decided by which library row was clicked.

export type Outcome = "verified" | "failed" | "not-found";

export type VerifiedDetails = {
  issuer: string;
  documentType: string;
  issuedDate: string;
  registeredDate: string;
  registeredBy: string;
};

export type FailedDetails = {
  issuer: string;
  documentType: string;
  reasons: string[];
};

export type NotFoundDetails = {
  issuer: string;
  reasons: string[];
};

export type DemoDocument = {
  id: string;
  filename: string;
  fileSize: string;
  assetPath: string;
  sha256: string;
  outcome: Outcome;
  verified?: VerifiedDetails;
  failed?: FailedDetails;
  notFound?: NotFoundDetails;
};

export const demoDocuments: DemoDocument[] = [
  // Education
  {
    id: "degree-cert",
    filename: "Degree Certificate.pdf",
    fileSize: "4.1 KB",
    assetPath: "/sample-documents/degree-cert.pdf",
    sha256: "ca496fb666c44ea234a23ecef4058e810ef47473d2dec19f625f17c06fad50d2",
    outcome: "verified",
    verified: {
      issuer: "Kweli University",
      documentType: "Degree Certificate",
      issuedDate: "17 March 2026",
      registeredDate: "17 March 2026 • 09:41 EAT",
      registeredBy: "Registrar Office",
    },
  },
  {
    id: "degree-cert-final",
    filename: "Degree Certificate Final.pdf",
    fileSize: "3.8 KB",
    assetPath: "/sample-documents/degree-cert-final.pdf",
    sha256: "3722b13f8a3f7edeee7b4ff8da6ad1c8c3286a5305d00d16b10245a2d2931629",
    outcome: "failed",
    failed: {
      issuer: "Kweli University",
      documentType: "Degree Certificate",
      reasons: ["Pages replaced", "Content modified"],
    },
  },
  {
    id: "degree-cert-scan",
    filename: "Degree Certificate Scan.pdf",
    fileSize: "4.3 KB",
    assetPath: "/sample-documents/degree-cert-scan.pdf",
    sha256: "798c50c1d13bbc4276ecc392decb7f551f2f9026064cc24d523face99e2a04c3",
    outcome: "not-found",
    notFound: {
      issuer: "Kweli University",
      reasons: ["Never registered", "Incorrect document"],
    },
  },
  // Insurance
  {
    id: "repair-estimate",
    filename: "Repair Estimate.pdf",
    fileSize: "6.8 KB",
    assetPath: "/sample-documents/repair-estimate.pdf",
    sha256: "0936fdd085658fb05500546dd1b5190b8ca62dcc3db5b9fd7a820ee0598dc3b5",
    outcome: "failed",
    failed: {
      issuer: "Northline Motors",
      documentType: "Repair Estimate",
      reasons: ["Edited", "Content modified"],
    },
  },
  {
    id: "repair-estimate-final",
    filename: "Repair Estimate Final.pdf",
    fileSize: "6.7 KB",
    assetPath: "/sample-documents/repair-estimate-final.pdf",
    sha256: "b65b6ad936e90eaa750353ded1ec0bb113e2258d2c807c04a9e7c318a7fdbed8",
    outcome: "verified",
    verified: {
      issuer: "Northline Motors",
      documentType: "Repair Estimate",
      issuedDate: "2 June 2026",
      registeredDate: "2 June 2026 • 14:12 EAT",
      registeredBy: "Claims Department",
    },
  },
  {
    id: "repair-estimate-copy",
    filename: "Repair Estimate Copy.pdf",
    fileSize: "6.8 KB",
    assetPath: "/sample-documents/repair-estimate-copy.pdf",
    sha256: "82b3923c7e619ee9159464ca853a2fac817d3ecdca39565bb0584b9d08b780cb",
    outcome: "not-found",
    notFound: {
      issuer: "Northline Motors",
      reasons: ["Never registered", "Incorrect document"],
    },
  },
  {
    id: "insurance-claim",
    filename: "Insurance Claim Form.pdf",
    fileSize: "5.8 KB",
    assetPath: "/sample-documents/insurance-claim.pdf",
    sha256: "68c0634bcf69029d3c83e4c1dddca5fdebd0858bc834a26442991c6003132b98",
    outcome: "verified",
    verified: {
      issuer: "Turaco Underwriters",
      documentType: "Insurance Claim Form",
      issuedDate: "9 May 2026",
      registeredDate: "9 May 2026 • 16:30 EAT",
      registeredBy: "Claims Department",
    },
  },
  // Healthcare
  {
    id: "lab-report",
    filename: "Laboratory Report.pdf",
    fileSize: "6.2 KB",
    assetPath: "/sample-documents/lab-report.pdf",
    sha256: "08278115794e08d8e4fe33ab2bfe08f591123031ee02d8ae44f474a44e1b7f94",
    outcome: "verified",
    verified: {
      issuer: "Verstlab Diagnostics",
      documentType: "Laboratory Report",
      issuedDate: "28 April 2026",
      registeredDate: "28 April 2026 • 11:05 EAT",
      registeredBy: "Records Office",
    },
  },
  {
    id: "lab-report-scan",
    filename: "Laboratory Report Scan.pdf",
    fileSize: "5.8 KB",
    assetPath: "/sample-documents/lab-report-scan.pdf",
    sha256: "1ab188be4e915496f046704c6f5876eba5a351834e0114af94a3631da82e4cd3",
    outcome: "not-found",
    notFound: {
      issuer: "Verstlab Diagnostics",
      reasons: ["Never registered", "Incorrect document"],
    },
  },
  // Trade
  {
    id: "organic-cert",
    filename: "Organic Certificate.pdf",
    fileSize: "4.1 KB",
    assetPath: "/sample-documents/organic-cert.pdf",
    sha256: "0326006300f78592b1ffdf0d818a3c8a848f83d7ff4a999d0d70c5164a49b9d8",
    outcome: "verified",
    verified: {
      issuer: "Cropnuts Certification Body",
      documentType: "Organic Certificate",
      issuedDate: "14 January 2026",
      registeredDate: "14 January 2026 • 08:52 EAT",
      registeredBy: "Certification Board",
    },
  },
  {
    id: "organic-cert-updated",
    filename: "Organic Certificate Updated.pdf",
    fileSize: "4.4 KB",
    assetPath: "/sample-documents/organic-cert-updated.pdf",
    sha256: "ecfeeab71affff76930c2fdc3ce2a58e11d6ffc4966fa910590262f3a0781526",
    outcome: "failed",
    failed: {
      issuer: "Cropnuts Certification Body",
      documentType: "Organic Certificate",
      reasons: ["Edited", "Content modified"],
    },
  },
  {
    id: "shipping-manifest",
    filename: "Shipping Manifest.pdf",
    fileSize: "5.8 KB",
    assetPath: "/sample-documents/shipping-manifest.pdf",
    sha256: "10ef31fc792f0263741874c5c691449e9b151fb187bdc2c8304e10cf42b31b3d",
    outcome: "failed",
    failed: {
      issuer: "Meridian Freight Lines",
      documentType: "Shipping Manifest",
      reasons: ["Edited", "Signature mismatch"],
    },
  },
  // Government
  {
    id: "building-permit",
    filename: "Building Permit.pdf",
    fileSize: "5.1 KB",
    assetPath: "/sample-documents/building-permit.pdf",
    sha256: "dd9c0b9b57401519e3b3b1e3f276db2aa628b856f3b5d80a01cc8f49ad4e49e3",
    outcome: "not-found",
    notFound: {
      issuer: "Unknown",
      reasons: ["Unknown issuer", "Incorrect document"],
    },
  },
  // Banking
  {
    id: "bank-guarantee",
    filename: "Bank Guarantee.pdf",
    fileSize: "4.8 KB",
    assetPath: "/sample-documents/bank-guarantee.pdf",
    sha256: "c59a3852e7ec13853f9c49ce0b677b2afc8d5838aa073b3846d18f7a420caef4",
    outcome: "verified",
    verified: {
      issuer: "Zenith Commercial Bank",
      documentType: "Bank Guarantee",
      issuedDate: "22 February 2026",
      registeredDate: "22 February 2026 • 10:18 EAT",
      registeredBy: "Branch Operations",
    },
  },
];

export function findDocumentByHash(sha256: string): DemoDocument | undefined {
  const normalized = sha256.toLowerCase();
  return demoDocuments.find((doc) => doc.sha256 === normalized);
}
