import {
  Car,
  Stethoscope,
  Flame,
  Ship,
  HardHat,
  Scale,
  Landmark,
  Plane,
  Heart,
  ClipboardList,
  Users,
  Briefcase,
  Building2,
  FileCheck2,
  Banknote,
  GraduationCap,
  Gavel,
  Vote,
  FileSearch,
  Truck,
  Anchor,
  Warehouse,
  Snowflake,
  Handshake,
  ShieldCheck,
  Award,
  BookOpen,
  IdCard,
  Pill,
  Microscope,
  HeartPulse,
  Syringe,
  Monitor,
  Mail,
  Fingerprint,
  Share2,
  BadgeCheck,
  Search,
  ClipboardCheck,
  Stamp,
  PackageCheck,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/lib/industryPageTypes";

// Shared by IndustryExplorer and IndustryWorkflowSection (journey steps),
// both client components. ExplorerLine.icon and JourneyStep.icon travel
// from a server component as serializable string keys, not component
// references, and get resolved to the real icon here.
export const ICONS: Record<IconName, LucideIcon> = {
  Car,
  Stethoscope,
  Flame,
  Ship,
  HardHat,
  Scale,
  Landmark,
  Plane,
  Heart,
  ClipboardList,
  Users,
  Briefcase,
  Building2,
  FileCheck2,
  Banknote,
  GraduationCap,
  Gavel,
  Vote,
  FileSearch,
  Truck,
  Anchor,
  Warehouse,
  Snowflake,
  Handshake,
  ShieldCheck,
  Award,
  BookOpen,
  IdCard,
  Pill,
  Microscope,
  HeartPulse,
  Syringe,
  Monitor,
  Mail,
  Fingerprint,
  Share2,
  BadgeCheck,
  Search,
  ClipboardCheck,
  Stamp,
  PackageCheck,
};
